Non humanoid animation sync and improved Fallout 4 player anim sync
tiltedphoques/TiltedOnline pull request #133
Opened 2021-07-24 13:36 UTC by RobbeBryssinck

To the best of my knowledge, the graphs for the majority of the different creatures have been analyzed and synchronized. It is possible that I have missed a few, but this should not result in a CTD, but instead possibly in a creature's animations not syncing. This can easily be reported and fixed, since I have left in the tool that I used for fetching the variables that need to be synced. The tool also checks for duplicate graph descriptors. This tool can be found in the TestService.

I also improved the Fallout 4 player animations by forcing the third person variables to be synced at all times.

Lastly, this PR also contains some foundational code for the equip manager for Fallout 4. I will expand on this in a later PR.

2021-07-25 11:18 UTC, yamashi requested changes

2021-07-25 11:18 UTC, yamashi commented on Code/client/Games/BSAnimationGraphManager.cpp
> +    return std::hash<String>{}(variableNames);
This isn’t stable as in, std::hash has no guarantee that it will return the same value in the future, use Crc64 or something similar instead in order to make sure we always get the same value

2021-07-25 11:20 UTC, yamashi commented
Nice work guys, very trial and error/grunt work but this will have a big quality of life impact

2021-07-25 12:02 UTC, RobbeBryssinck commented on Code/client/Games/Fallout4/Actor.cpp
> +    /*
This is part of the EquipManager for Fallout 4, which was not implemented before. I'm still developing it, and this function call crashes the game, but I didn't want to throw it away. I'm expanding on it in a different branch.

2021-07-25 12:03 UTC, RobbeBryssinck commented on Code/client/Games/BSAnimationGraphManager.cpp
In an earlier version of the keygen system, the ordering of the variables mattered. This is not the case anymore, so an unordered_map will do fine. I will change this in a bit. Not sure why I didn't return it, I'll change that too.

2021-07-25 12:32 UTC, RobbeBryssinck commented on Code/client/Games/BSAnimationGraphManager.cpp
On second thought, the ordering of the variables does still matter, since the output is displayed in order. These functions are rarely called, since the keys are cached, so performance shouldn't be an issue. Unless there are any major objections, I'd suggest keeping std::map.

2021-07-25 12:33 UTC, yamashi commented on Code/client/Games/BSAnimationGraphManager.cpp
Use tilted core's map, not STL containers directly

2021-08-11 21:30 UTC, yamashi commented
Just checking if there is any update regarding this pr

2021-08-11 21:32 UTC, RobbeBryssinck commented
Some things unrelated to the project came up, but I'll finish the PR somewhere in the next few days.

2021-08-14 18:12 UTC, merged