Update UI to Angular 10, to prepate the UI reborn :)
tiltedphoques/TiltedOnline pull request #62
Opened 2020-08-28 00:05 UTC by Dumbeldor

2020-08-28 00:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tiltedphoques/TiltedOnline?pullRequest=62) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tiltedphoques/TiltedOnline?pullRequest=62) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tiltedphoques/TiltedOnline?pullRequest=62) it.</sub>

2020-08-30 12:59 UTC, yamashi requested changes

2020-08-30 12:59 UTC, yamashi commented on Code/client/include/Services/OverlayService.h
> +    bool GetActive();
[[nodiscard]] bool IsActive() const noexcept;

2020-08-30 12:59 UTC, yamashi commented on Code/client/include/Services/OverlayService.h
> +    void SetActive(bool aActive);
noexcept

2020-08-30 12:59 UTC, yamashi commented on Code/client/include/Services/OverlayService.h
> +    void Render();
noexcept

2020-08-30 12:59 UTC, yamashi commented on Code/client/include/Services/OverlayService.h
> +    void Initialize();
noexcept

2020-08-30 12:59 UTC, yamashi commented on Code/client/include/Services/OverlayService.h
> +    bool GetInGame();
[[nodiscard]] bool IsInGame() const noexcept;

2020-08-30 12:59 UTC, yamashi commented on Code/client/include/Services/OverlayService.h
> +    void SetInGame(bool aInGame);
noexcept

2020-09-02 19:27 UTC, Dumbeldor commented on Code/client/include/Services/OverlayService.h
> +    bool GetActive();
Thanks, it's nice !

2020-09-03 20:49 UTC, Dumbeldor commented
I added checkboxes to follow the evolution of PR. And this PR depends on this one https://github.com/tiltedphoques/TiltedUI/pull/9

2020-12-21 18:01 UTC, algorithmhash commented
Gyp error could be resolved with yarn fix by installing with yarn. I can start here and take a look. Thanks @yamashi .

2021-02-19 13:05 UTC, Dragonisser commented
I fixed disconnecting and chat on my fork on the feature/updated_ui branch

2021-12-15 11:38 UTC, closed without merging